# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='\u0422\u0438\u043f \u0436\u0438\u043b\u044c\u044f')),
                ('placement_type', models.CharField(max_length=255, verbose_name='\u0422\u0438\u043f \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f')),
                ('guest_count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0433\u043e\u0441\u0442\u0435\u0439')),
                ('traditional_places_count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0442\u0440\u0430\u0434\u0438\u0446\u0438\u043e\u043d\u043d\u044b\u0445 \u043c\u0435\u0441\u0442')),
                ('bedroom_count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0441\u043f\u0430\u043b\u0435\u043d')),
                ('bed_count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u0440\u043e\u0432\u0430\u0442\u0435\u0439')),
                ('bath_count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0431\u0430\u043d\u044c')),
                ('shower_in_house_count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u0443\u0448\u0435\u0432\u044b\u0445 \u0432 \u0434\u043e\u043c\u0435')),
                ('shower_on_street_count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u0443\u0448\u0435\u0432\u044b\u0445 \u043d\u0430 \u0443\u043b\u0438\u0446\u0435')),
                ('bathroom_count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u0430\u043d\u043d\u044b\u0445')),
                ('inside_toilet_count', models.IntegerField(verbose_name='\u0412\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0438\u0439 \u0442\u0443\u0430\u043b\u0435\u0442. \u0423\u043d\u0438\u0442\u0430\u0437')),
                ('inside_turkish_count', models.IntegerField(verbose_name='\u0412\u043d\u0435\u0442\u0440\u0435\u043d\u043d\u0438\u0439 \u0442\u0443\u0430\u043b\u0435\u0442. \u0422\u0443\u0440\u0435\u0446\u043a\u0438\u0439')),
                ('region', models.CharField(max_length=255, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
                ('city', models.CharField(max_length=255, verbose_name='\u0413\u043e\u0440\u043e\u0434/\u0420\u0430\u0439\u043e\u043d')),
                ('street', models.CharField(max_length=255, verbose_name='\u0423\u043b\u0438\u0446\u0430')),
                ('house_number', models.CharField(max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0434\u043e\u043c\u0430')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u0441\u0443\u0442\u043a\u0438')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0436\u0438\u043b\u044c\u044f')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0436\u0438\u043b\u044c\u044f')),
                ('check_in_time', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u0435\u0437\u0434\u0430')),
                ('departure_time', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432\u044b\u0435\u0437\u0434\u0430')),
            ],
            options={
                'db_table': 'accommodations',
                'verbose_name': '\u0416\u0438\u043b\u044c\u0451',
                'verbose_name_plural': '\u0416\u0438\u043b\u0438\u0449\u0430',
            },
        ),
        migrations.CreateModel(
            name='ComfortSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('value', models.BooleanField(verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0423\u0434\u043e\u0431\u0441\u0442\u0432\u0430',
                'verbose_name_plural': '\u0423\u0434\u043e\u0431\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='\u0428\u0438\u0440\u043e\u0442\u0430')),
                ('longitude', models.FloatField(verbose_name='\u0414\u043e\u043b\u0433\u043e\u0442\u0430')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u0430\u0440\u043a\u0438')),
            ],
            options={
                'db_table': 'coordinates',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('title', models.CharField(max_length=255, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.AddField(
            model_name='accommodations',
            name='comfort_settings',
            field=models.ManyToManyField(to='cbt_models.ComfortSettings', verbose_name='\u0423\u0434\u043e\u0431\u0441\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='accommodations',
            name='coords',
            field=models.ManyToManyField(to='cbt_models.Coordinates', verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='accommodations',
            name='preview',
            field=models.ManyToManyField(to='cbt_models.Media', verbose_name='\u0424\u043e\u0442\u043e \u0436\u0438\u043b\u044c\u044f'),
        ),
    ]
