# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
