# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_models', '0006_auto_20170107_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='preview',
            field=models.ImageField(upload_to='', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
