# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_models', '0007_auto_20170107_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='is_automatic',
            field=models.BooleanField(default=False, verbose_name='\u041c\u0433\u043d\u043e\u0432\u0435\u043d\u043d\u043e\u0435 \u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
