# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_models', '0008_accommodations_is_automatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comfortsettings',
            name='value',
        ),
    ]
