# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_models', '0009_remove_comfortsettings_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
            ],
            options={
                'db_table': 'date_helper',
            },
        ),
        migrations.AddField(
            model_name='accommodations',
            name='reserved_days',
            field=models.ManyToManyField(to='cbt_models.DateHelper', verbose_name='\u0417\u0430\u0440\u0435\u0437\u0435\u0440\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u0434\u043d\u0438'),
        ),
    ]
