# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_models', '0010_auto_20170113_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='book_days',
            field=models.ManyToManyField(related_name='book_days', to='cbt_models.DateHelper', verbose_name='\u0417\u0430\u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u0434\u043d\u0438'),
        ),
        migrations.AlterField(
            model_name='accommodations',
            name='reserved_days',
            field=models.ManyToManyField(related_name='reserved_days', to='cbt_models.DateHelper', verbose_name='\u0417\u0430\u0440\u0435\u0437\u0435\u0440\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u0434\u043d\u0438'),
        ),
    ]
