# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_models', '0011_auto_20170113_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'accommodation_type',
                'verbose_name': '\u0422\u0438\u043f \u0436\u0438\u043b\u044c\u044f',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0436\u0438\u043b\u044c\u044f',
            },
        ),
        migrations.AlterModelOptions(
            name='datehelper',
            options={'verbose_name': '\u0414\u0430\u0442\u0443', 'verbose_name_plural': '\u0414\u0430\u0442\u044b'},
        ),
        migrations.RemoveField(
            model_name='accommodations',
            name='inside_turkish_count',
        ),
        migrations.AddField(
            model_name='accommodations',
            name='outside_toilet_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0412\u043d\u0435\u0448\u043d\u0438\u0439 \u0442\u0443\u0430\u043b\u0435\u0442.'),
        ),
        migrations.AlterField(
            model_name='accommodations',
            name='book_days',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_days', to='cbt_models.DateHelper', verbose_name='\u0417\u0430\u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u0434\u043d\u0438'),
        ),
        migrations.AlterField(
            model_name='accommodations',
            name='reserved_days',
            field=models.ManyToManyField(blank=True, null=True, related_name='reserved_days', to='cbt_models.DateHelper', verbose_name='\u0417\u0430\u0440\u0435\u0437\u0435\u0440\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u0434\u043d\u0438'),
        ),
        migrations.AlterField(
            model_name='accommodations',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_models.AccommodationType', verbose_name='\u0422\u0438\u043f \u0436\u0438\u043b\u044c\u044f'),
        ),
    ]
