# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibiti_models', '0005_accommodations_has_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('preview', models.ImageField(upload_to='/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'star',
                'verbose_name': '\u0417\u0432\u0451\u0437\u0434\u0430',
                'verbose_name_plural': '\u0417\u0432\u0451\u0437\u0434\u044b',
            },
        ),
        migrations.AddField(
            model_name='accommodations',
            name='stars',
            field=models.ManyToManyField(blank=True, null=True, to='sibiti_models.Star', verbose_name='\u0417\u0432\u0451\u0437\u0434\u044b'),
        ),
    ]
